service: uow-parking
app: uow-parking
tenant: ramblingenzyme
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

package:
  include:
    - node_modules/**

functions:
  uow-parking:
    handler: handler.bot
    events:
      - schedule:
          rate: cron(30,0 7-19 * * ? *)
          timezone: Australia/Sydney
    environment:
      TZ: Australia/Sydney
      CONSUMER_KEY: ${ssm:twitter-api-key}
      CONSUMER_SECRET: ${ssm:twitter-api-secret}
      ACCESS_TOKEN: ${ssm:twitter-token}
      ACCESS_SECRET: ${ssm:twitter-token-secret}


plugins:
  - serverless-local-schedule
